name: flash_chat
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


flutter_icons:
  image_path: "images/logo.png"
  android: true
  ios: true
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  modal_progress_hud_nsn:
  flutter_launcher_icons:  



dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - images/

  
 
